config/routes.rb
Mwiki::Application.routes.draw do

  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

  resources :articles do
    member do
      get 'history'
      get 'revert'
    end
  end

  devise_for :users

  root :to => "home#index"
end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as_taggable
  has_paper_trail :on => [ :create, :update, :destroy ]

  belongs_to :user

  def to_s
    name
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
              
  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  
  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name
	
	def url_thumb
	  @url_thumb ||= begin
	    extname = File.extname(filename).gsub(/^\./, '')
      "/javascripts/ckeditor/filebrowser/images/thumbs/#{extname}.gif"
	  end
	end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name
	
	def url_content
	  url(:content)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def info_for_paper_trail
    {:ip => request.remote_ip, :user_agent => request.user_agent}
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.where(:id => params[:id]).first
    redirect_to articles_path and return unless @article

    if @article and params[:v]
      @version = Version.find params[:v]
      @article = @version.reify
    end


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end


  # GET /articles/1
  # GET /articles/1.json
  def history
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created. #{undo_link}" }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])


    respond_to do |format|
      if @article.update_attributes(params[:article])
        undo_link = view_context.link_to("undo", revert_version_path(@article.versions.last), :method => :post)
        format.html { redirect_to @article, notice: "Article was successfully updated. #{undo_link}" }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, :notice => "Successfully destroyed article. #{undo_link}" }
      format.json { head :ok }
    end
  end

  def undo_link
     view_context.link_to("undo", revert_version_path(@article.versions.scoped.last), :method => :post)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  @articles = Article.all(:order => "id desc", :limit => 3)
  end

end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  def revert
    @version = Version.find(params[:id])
    if @version.reify
      @version.reify.save
    else
      @version.item.destroy
    end

    link_name = params[:redo] == "true" ? "undo" : "redo"
    link = view_context.link_to(link_name, revert_version_path(@version.next, :redo => !params[:redo]), :method => :post)
    redirect_to :back, :notice => "Undid #{@version.event}. #{link}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/articles/_form.html.erb
<div class="row">
  <div class="span16">
    <%= form_for(@article) do |f| %>
      <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

          <ul>
            <% @article.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>


      <fieldset>

        <div class="clearfix ">
          <label for="xlInput4">name</label>
          <div class="input">
            <%= f.text_field :name, :class => " span13", :size => 30 %>
          </div>
        </div><!-- /clearfix -->


        <div class="clearfix">
          <label for="textarea">Content</label>
          <div class="input">
            <%= f.cktext_area :content, :toolbar => "Full", :width => 800, :height => 400 %>
            <span class="help-block">
              Block of help text to describe the field above if need be.
            </span>
          </div>
        </div><!-- /clearfix -->

      </fieldset>

      <div class="actions">
        <%= f.submit "Save changes", :class => "btn primary"%>
        &nbsp;<button type="reset" class="btn">Cancel</button>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/_tab.html.haml
%ul.pills

  %li{ :class => "right #{'active' if params[:action] == 'showb'}" }
    = link_to "Add to Favorite"

  %li{ :class => "right #{'active' if params[:action] == 'history'}" }
    = link_to "View history", history_article_path(@article)

  %li{ :class => "right #{'active' if params[:action] == 'edit'}" }
    = link_to "Edit", edit_article_path(@article)

  %li.right
  %li{ :class => "right #{'active' if params[:action] == 'show'}" }
    = link_to "Read", @article




  %li{ :class => " #{'active' if params[:controller] == "articles" }" }
    = link_to "Article", "#"
  %li{ :class => " #{'active' if params[:controller] != "articles" }" }
    = link_to "Discussion", "#"

app/views/articles/edit.html.haml
.wiki
  = render "articles/tab"
  %section{:id => "forms"}
    %div.page-header
      %h1
        = "Edit Wiki"
    = render 'form'
    = link_to 'Show', @article
    = '|'
    = link_to 'Back', articles_path

app/views/articles/history.html.haml
.wiki
  = render "articles/tab"
  .page-header
    %h1
      = @article.name
  .row
    .span16
      %table
        %tr
          %td Version
          %td Name
          %td Changed At
          %td


        %tr
          %td
            %span.label.default
              Current
          %td
            = link_to @article, article_path(@article)
          %td
            = @article.updated_at
          %td


        - @article.versions.reverse.each do |v|
        - art = v.reify
          %tr
            %td
              %span{ :class => "label #{{'create' =>  'success', 'update' => 'warning', 'destroy' => 'important'}[v.event]  }" }
                =  v.event
            %td
              = link_to art, article_path(art, :v => v.id) unless art.blank?
            %td
              = v.created_at
            %td
              = link_to "Revert", revert_version_path(v), :method => :post, :class => "btn danger" if v.event != "create"
              = link_to "Undo", "#", :class => "btn danger" if v.event != "create"

app/views/articles/index.html.haml
%h1 "Listing Wiki"
%table
  %tr
    %th
      "Name"
    %th
  - @articles.each do |article|
    %tr
      %td
        = link_to article, article
      %td
        = link_to 'Edit', edit_article_path(article), :class => "btn info"
        = link_to 'Destroy', article,  method: :delete, :class => "btn danger"


= link_to 'New Wiki', new_article_path, :class => "btn success"

app/views/articles/new.html.haml
.wiki
  %section{:id => "forms"}
    %div.page-header
      %h1
        = "New Wiki"
      = link_to 'Back', articles_path, :class => "title_link"
    = render 'form'
    = link_to 'Show', @article

app/views/articles/show.html.haml
.wiki
  = render "articles/tab"
  .page-header
    %h1
      = link_to "Previous", article_path(@article,  @version.previous.id), :class => :title_link if @article and @version
      = link_to "Newer", article_path(@article, :v => @article.next_version.id) if !@article.live? and !@article.next_version.blank?
      = @article.name
  .row
    .span16
      .well
        %div
          %p.muted
            = @article.content.html_safe


      = link_to 'Edit', edit_article_path(@article)
      = link_to 'Back', articles_path

app/views/home/index.html.haml
.hero-unit
  %h1 "Wiki!!"
  %p "Add a wiki!!. "
  %p
    = link_to "Create Wiki", new_article_path, :class => "btn primary large"

.row
  - @articles.each do |article|
    %div{ :class => (article == @articles.first ? "span6" : "span5")}
      %h2
        = article.name
      %p
        = h article.content.html_safe
      %p
        = link_to "View details &raquo;".html_safe, article, :class => "btn"

app/views/layouts/application.html.haml
!!!
%head
  %title= content_for?(:title) ? "Mwiki - "+ yield(:title) : "Mwiki"
  %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
  <![endif]-->

  %link{ :rel=>"shortcut icon", :href=>"images/favicon.ico"}
  %link{ :rel=>"apple-touch-icon", :href=>"images/apple-touch-icon.png"}
  %link{ :rel=>"apple-touch-icon", :sizes=>"72x72", :href=>"images/apple-touch-icon-72x72.png"}
  %link{ :rel=>"apple-touch-icon", :sizes=>"114x114", :href=>"images/apple-touch-icon-114x114.png"}

  = stylesheet_link_tag   "application"
  = javascript_include_tag "application", '/javascripts/ckeditor/ckeditor.js'
  = javascript_include_tag "http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"
  = csrf_meta_tag
  -#= render :partial=>'layouts/google'
  -#= yield(:head)
%body

  = render "shared/top_bar"
  .container
    = render "shared/side_bar"
    .content
      -#= render(:partial=> 'layouts/app_navigation')
      -# flash.each do |name, msg|
        -#= content_tag :div, msg, :id => "flash_#{name}"
      - flash.each do | name, msg|
        %div{ :class => "alert-message  #{name}"}
          = link_to "x", "#", :class => "close"
          %p
            %strong
              = raw(msg)

      = yield

    = render "shared/footer"

app/views/shared/_footer.html.haml
%footer
  %p "&copy; MWiki 2011"

app/views/shared/_side_bar.html.haml
- if params[:controller] == "home" and false
  .sidebar
    .well
      %h5 Sidebar
      %ul
        %li
          = link_to "Link", "#"
        %li
          = link_to "Link", "#"

      %h5 Sidebar
      %ul
        %li
          = link_to "Link", "#"
        %li
          = link_to "Link", "#"

app/views/shared/_top_bar.html.haml
.topbar
  .topbar-inner
    .container-fluid
      =  link_to "Mwiki", root_path, :class => "brand"
      %ul.nav
        %li{:class => params[:controller] == "home"  ? "active" : ""}
          = link_to "Home", root_path
        %li{:class => params[:controller] == "articles"  ? "active" : ""}
          = link_to "Wiki", articles_path
        %li
          = link_to "About", "#"
        %li
          = link_to "Contact", "#"

      %p.pull-right
        = link_to "Create a wiki", new_article_path, :class => "btn success"

        - if user_signed_in?
          = link_to "Log Out", destroy_user_session_path, :method => :delete
        - else
          = link_to 'Sign up', new_user_registration_path, :id => 'signup_link'
          or
          = link_to 'Sign in', new_user_session_path, :id => 'signin_link'